# Generated by Django 4.2 on 2023-05-02 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.TextField(default="")),
                ("created_on", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(default="")),
                ("created_on", models.DateTimeField(auto_now=True)),
                (
                    "answer_number",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="chatbot.answer"
                    ),
                ),
            ],
        ),
    ]
